
#Client configuration settings
[general]
	#Display the goggles before the eyes and not on the forehead
	moveGoggleToEyes = false
	#Enables the goggles in creative mode without goggles
	enableCreativeModeGoggles = true

