
[air]
	#Range: > 1
	uses_per_tank = 2048
	#Range: > 1
	uses_per_tank_hover = 20480

[speed]
	#Range: 0.01 ~ 100.0
	horizontal = 0.02
	#Range: 0.01 ~ 100.0
	acceleration = 0.6
	#Range: 0.0 ~ 100.0
	swim_modifier = 1.8
	#Range: 0.01 ~ 100.0
	vertical = 0.4
	#Range: -100.0 ~ 0.0
	hover_descend = -0.03

[features]
	elytra_boost = true

