
#General configuration options.
[General]
	#If enabled, any tags in the cucumber-tags.json file set to items that don't exist will be refreshed if possible.
	autoRefreshTagOptions = true
	#Mod ids (in order) to prioritize using items for when generating the cucumber-tags.json file.
	modTagPriorities = ["techreborn", "indrev", "ae2"]

