
["Button Position"]
	#Pixels away from the bottom left of the GUI in the x axis
	#Range: > 0
	X = 25
	#Pixels away from the bottom left of the GUI in the y axis
	#Range: > 0
	Y = 0
	NAME = "Dark Mode"

["Main Menu Button"]
	#Pixels away from the bottom left of the GUI in the x axis
	#Range: > 0
	X = 4
	#Pixels away from the bottom left of the GUI in the y axis
	#Range: > 0
	Y = 40
	#Enabled
	SHOW = false
	NAME = "Dark Mode"

