blacklistedOres = []
enableNoEmiMessage = true
spawnWithGuideBook = true
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = true
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = false
enableAe2Integration = true
generateOres = true
datagenOnStartup = false
loadRuntimeGeneratedResources = true
