#Mutant Creeper spawn weight.
#Range: 0 ~ 100
mutant_creeper_spawn_weight = 5
#Mutant Enderman spawn weight.
#Range: 0 ~ 100
mutant_enderman_spawn_weight = 5
#Mutant Skeleton spawn weight.
#Range: 0 ~ 100
mutant_skeleton_spawn_weight = 5
#Mutant Zombie spawn weight.
#Range: 0 ~ 100
mutant_zombie_spawn_weight = 5
#When infested with a Mutant X potion, what mutant mob should the target transform into. Otherwise the target will ony explode and take damage.
#Format for every entry is "<namespace>:<path>,<namespace>:<path>" with the second id representing the mutant. Namespace may be omitted to use "minecraft" by default.
mutant_x_conversions = ["minecraft:creeper,mutantmonsters:mutant_creeper", "minecraft:enderman,mutantmonsters:mutant_enderman", "minecraft:skeleton,mutantmonsters:mutant_skeleton", "minecraft:snow_golem,mutantmonsters:mutant_snow_golem", "minecraft:zombie,mutantmonsters:mutant_zombie", "minecraft:pig,mutantmonsters:spider_pig"]

