
#General settings
[general]
	#Placement range for switches
	#Range: 16 ~ 128
	switchPlacementRange = 64
	#Maximum length of conductor vents
	#Range: > 1
	maxConductorVentLength = 64
	#Allow controlling Brass Switches remotely when approaching them on a train
	flipDistantSwitches = true
	#Outside-of-render-distance train sync time (in ticks)
	#Range: 10 ~ 600
	farTrainUpdateTicks = 200
	#Conductor whistle is limited to the owner of a train
	mustOwnBoundTrain = false
	#Coupler will require points to be on the same or adjacent track edge, this will prevent the coupler from working if there is any form of junction in between the two points.
	strictCoupler = false
	#In-render-distance train sync time (in ticks)
	#Range: 1 ~ 600
	nearTrainUpdateTicks = 1
	#Disable Steam 'n Rails datafixers. Do not enable this config if you world contains pre-Create 0.5.1 monobogeys, because then they will be destroyed
	disableDatafixer = false
	#Register integration tracks for mods that are not present
	registerMissingTracks = false

#Semaphore settings
[semaphore]
	#Whether semaphore color order is reversed when the semaphores are oriented upside-down
	semaphoresFlipYellowOrder = false
	#Simplified semaphore placement
	simplifiedSemaphorePlacement = true

