
#General settings
[general]
	#Show extended debug info in coupler goggle overlay
	extendedCouplerDebug = false
	#Journeymap train overlay old marker removal check time (in ticks)
	#Range: 10 ~ 1200
	journeymapObsolescenceCheckTicks = 200
	#Journeymap train overlay update time (in ticks)
	#Range: 1 ~ 600
	journeymapUpdateTicks = 1

