
[slicer]
	consume_tool_durability = true
	ignore_rotation = false

[basin_cooking]
	enabled = true

[sprinkler]
	#Range: 10 ~ 2048
	fluid_capacity = 300
	#Range: 0 ~ 2048
	fluid_per_use = 100

