#The chance a non-boss entity from a supported mod drops a trophy when killed by a player
#No trophies will drop from entities when this value is set to 0
#Range: 0.0 ~ 1.0
trophy_chance = 0.001
#Whether trophies can drop loot when right-clicked
enable_trophy_loot = true
#Whether trophies can apply status effects when right-clicked
enable_trophy_effects = true

